In [1]:
## Image segmentaion using projection method

import cv2
import numpy as np
import matplotlib.pyplot as plt
# Load as greyscale
im = cv2.imread('nep.jpg', cv2.IMREAD_GRAYSCALE)
(thresh, im) = cv2.threshold(im, 128, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
print(im)
# Invert
# im = 255 - im
count=0
# Calculate horizontal projection
proj = np.sum(im,1)

# Create output image same height as text, 500 px wide
# m = np.max(proj)
# w = 500
result = np.zeros((proj.shape[0],500))

# Draw a line for each row
# for row in range(im.shape[0]):
#     cv2.line(result, (0,row), (int(proj[row]*w/m),row), (255,255,255), 1)
# print(proj)
for i in proj:
    count+=1

    if i>(np.max(proj)-500):
        cv2.line(im, (0, count), (400, count), (0,255,0), 2)
        cv2.imwrite('result.png', im)
        plt.imshow(im)
# Save result

# print(count)
# print(np.max(proj))
# print(im.size)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]]
